/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kyakya.icu.javalin.demo

import io.javalin.Javalin
import kyakya.icu.javalin.demo.config.Modules
import kyakya.icu.javalin.demo.web.HttpRouter
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import org.koin.core.context.startKoin

class App : KoinComponent {
    private val app: Javalin = Javalin.create()
    private val router by inject<HttpRouter>()

    init {
        router.register(app)
    }

    fun start() {
        app.start(7070)
    }
}

fun main() {
    // start Koin!
    startKoin {
        // declare modules
        modules(Modules.getAllModules())
    }
    App().start()
}
